
SET SERVEROUTPUT ON
DECLARE
/*

    +  SUMA
    -  RESTA
    *  MULTIPLICACIÓN
    ** EXPONENCIAL
    /  DIVISION
    || CONCATENAR

*/
    X NUMBER;
    Y NUMBER;
    Z VARCHAR(100);
    Z2 VARCHAR2(100);
BEGIN

X := 20;
Y:=2;
Z := 'jAVIER ESTEBAN';
Z2:= 'TIBURCIO ORTEGA';

DBMS_OUTPUT.PUT_LINE( ' Resultado de la Suma.' || TO_CHAR((X + Y)));
DBMS_OUTPUT.PUT_LINE(X * Y);
DBMS_OUTPUT.PUT_LINE(X / Y);
DBMS_OUTPUT.PUT_LINE(X ** Y);

DBMS_OUTPUT.PUT_LINE( LOWER(Z) ||'  '|| UPPER(Z2)); 

END;


